# Generated by Django 5.0.6 on 2024-09-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='bar_chart',
            field=models.ImageField(blank=True, null=True, upload_to='charts/'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='donut_chart',
            field=models.ImageField(blank=True, null=True, upload_to='charts/'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='line_chart',
            field=models.ImageField(blank=True, null=True, upload_to='charts/'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='pie_chart',
            field=models.ImageField(blank=True, null=True, upload_to='charts/'),
        ),
    ]
