# Generated by Django 5.0.6 on 2024-09-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analysisresult_bar_chart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
    ]
